#ifndef _COMMON_HEADER
#define _COMMON_HEADER

/* The user can enable any one of the below defines */

/* This define should be used when the user wants lesser ROM usage by the font tables.
 * The font tables are stored in the bit encoded format - i.e. 8 pixel values stored as 1 byte
 * Since the bit decoding has to be done, this method uses less memory and more time.
 * In order to further reduce the time, another implementation has been supported - in which
 * each font details (font table names) are given as switch. This method will have reduced execution
 * time but stack usage will be more
 * This method expects the user to extend the switch case
 */
//#define _SPEED_OPTIMIZED_LESS_ROM
/* This define should be used when the user wants lesser ROM usage by the font tables.
 * The font tables are stored in the bit encoded format - i.e. 8 pixel values stored as 1 byte
 * Since the bit decoding has to be done, this method uses less memory and more time.
 * This method expects the user to fill the look up table in the character_specific_includes.h
 * Since each pixel value is read by calling function, this is time consuming, but optimized for
 * ROM and stack sizes
 */

//#define _SIZE_OPTIMIZED_LESS_ROM

/* This define can be used if the user wants to store each pixel of the font table separately.
 * This method helps to speed up the process because we can avoid the bit decoding, but occupies
 * a very huge memory because each pixel value occupies a byte in the memory
 * This method expects the user to extend the switch case
 * When using this define the font tables should be generated by commenting the define
 * ROM_OPTIMIZED (in the main.c in the FontGeneration folder)
 */
#define _SPEED_OPTIMIZED_EXCESS_ROM


typedef enum
{
	DISPLAY_MONOCHROME,
	DISPLAY_RGB555
}graphics_displayoption;

#ifndef _SPEED_OPTIMIZED_EXCESS_ROM
typedef enum
{
	Arial = 0,
	Arial_Italic = 1,
	Arial_Bold = 2,
	TimesNewRoman = 3,
	TimesNewRoman_Italic = 4,
	TimesNewRoman_Bold = 5,
	FontNotSupported = 0xFF
}font_support_list;

#define FONT0_TABLENAME Arial_Normal16
#define FONT0_OFFSETTABLE Arial_Normal_lookuptable
#define FONT1_TABLENAME Arial_Italic16
#define FONT1_OFFSETTABLE Arial_Italic_lookuptable
#define FONT2_TABLENAME Arial_Bold16
#define FONT2_OFFSETTABLE Arial_Bold_lookuptable
#define FONT3_TABLENAME TimesNew_Normal16
#define FONT3_OFFSETTABLE TimesNew_Normal_lookuptable
#define FONT4_TABLENAME TimesNew_Italic16
#define FONT4_OFFSETTABLE TimesNew_Italic_lookuptable
#define FONT5_TABLENAME TimesNew_Bold16
#define FONT5_OFFSETTABLE TimesNew_Bold_lookuptable

#else

/* The font support has to be reduced because of the huge ROM size requirement */
typedef enum
{
	Arial = 0,
	TimesNewRoman = 1,
    FontNotSupported = 0xFF
}font_support_list;

#define FONT0_TABLENAME Arial_Normal16
#define FONT0_OFFSETTABLE Arial_Normal_lookuptable
#define FONT1_TABLENAME TimesNew_Normal16
#define FONT1_OFFSETTABLE TimesNew_Normal_lookuptable

#endif




#endif
