SPHINX_PROJECT_NAME=LCD Display Module
VERSION=1.0
DOXYGEN_DIRS= ../module_lcd/src ../module_touch_controller_lib/src ../module_touch_controller_server/src 
SOURCE_INCLUDE_DIRS= ../module_lcd/src ../module_touch_controller_lib/src ../module_touch_controller_server/src 
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
