#ifndef TOUCH_CONTROLLER_CONF_H_
#define TOUCH_CONTROLLER_CONF_H_

//#define LCD_TS_PART_NUMBER K430WQA-V5-F
//#define LCD_WIDTH 480
//#define LCD_HEIGHT 272
//#define TS_WIDTH 4096
//#define TS_HEIGHT 4096

#endif /* TOUCH_CONTROLLER_CONF_H_ */
