all: html

SPHINX_PROJECT_NAME = Touch Controller Simple Demo Quickstart
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../app_touch_controller_lib_demo
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
