all: html

SPHINX_PROJECT_NAME = Touch Controller Server Demo Quickstart
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../app_touch_controller_server_demo
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc