SPHINX_PROJECT_NAME=Graphics LCD Display
VERSION=1.0
DOXYGEN_DIRS= ../app_graphics_demo/src ../module_lcd/src ../module_sdram_burst_new/src
SOURCE_INCLUDE_DIRS= ../app_graphics_demo/src ../module_lcd/src ../module_sdram_burst_new/src
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc