SPHINX_PROJECT_NAME=LCD Display Module
VERSION=1.0
DOXYGEN_DIRS= ../app_graphics_demo/src ../module_lcd/src 
SOURCE_INCLUDE_DIRS= ../app_graphics_demo/src ../module_lcd/src 
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc
