SPHINX_PROJECT_NAME=Graphics LCD Display
VERSION=1.0
DOXYGEN_DIRS= ../app_graphics_demo/src ../module_lcd/src ../app_image_rotation/src
SOURCE_INCLUDE_DIRS= ../app_graphics_demo/src ../module_lcd/src ../app_image_rotation/src
XDOC_DIR ?= ../../xdoc
include $(XDOC_DIR)/Makefile.inc